baseurl = "https://naist-se.github.io/" 
title = "Software Engineering Laboratory - NAIST"
theme = "hugo-universal-theme"
themesDir = "themes/"
languageCode = "en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
[languages]

  [languages.ja]
    contentDir = 'content/ja'
    disabled = false
    languageCode = 'ja'
    languageName = '日本語'
    title = 'ソフトウェア工学研究室'
    weight = 1
    [languages.ja.params]
      about_us = "<p>奈良先端科学技術大学院大学</br>先端科学技術研究科 情報科学領域</br>〒630-0192 奈良県生駒市高山町8916-5</p>"
    [languages.ja.menu]

[[languages.ja.menu.main]]
        name = 'ニュース'
        url = '/ja/news'
        weight = 1
[[languages.ja.menu.main]]
        name = '業績'
        url = "/ja/publish/"
        weight = 2
[[languages.ja.menu.main]]
    name       = "研究テーマ"
    identifier = "research"
    url        = "/ja/research/"
    weight     = 3
[[languages.ja.menu.main]]
    name       = "研究室の様子"
    identifier = "life"
    url        = "/ja/life/"
    weight     = 4
[[languages.ja.menu.main]]
    name       = "アクセス・問い合わせ"
    identifier = "menu.access"
    url        = "/ja/access/"
    weight     = 5

[languages.ja.params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "ソフトウェアは成長する、あなたとともに"
    subtitle = "研究内容がプログラミングと密接に関係するため、プログラミング経験があると研究をスムーズに進めることができます。また、ベクトルや集合、グラフといった数学の基礎的な概念を知っていると役立ちます。"
    link_url = "https://naist-se.github.io/"
    link_text = "Homepage"

[languages.ja.params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "研究スタッフ"

  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageName = 'English'
    title = 'Software Engineering Lab'
    weight = 2
    [languages.en.params]
    copyright = "<p> © 2013-2023 Software Engineering Laboratory, Graduate School of Information Science, Nara Institute of Science and Technology, All rights reserved.</p>"
    [languages.en.menu]

[[languages.en.menu.main]]
        name = 'News'
        url = '/ja/news'
        weight = 1
[[languages.en.menu.main]]
        name = 'Publications'
        url = "/ja/publish/"
        weight = 2
[[languages.en.menu.main]]
    name       = "Research"
    identifier = "research"
    url        = "/ja/research/"
    weight     = 3
[[languages.en.menu.main]]
    name       = "Research Life"
    identifier = "life"
    url        = "/ja/life/"
    weight     = 4
[[languages.en.menu.main]]
    name       = "Access"
    identifier = "menu.access"
    url        = "/ja/access/"
    weight     = 5

[languages.en.params.testimonials]
    enable = true
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Faculty Members"

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

# not pluralize title pages by default
pluralizelisttitles = false

# Top bar social links menu
[[languages.ja.menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/NAIST-SE/naist-se.github.io"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[languages.ja.menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/selabnaist/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[languages.ja.menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/naistselab"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[languages.en.menu.topbar]]
    weight = 2
    name = "GitHub"
    url = "https://github.com/NAIST-SE/naist-se.github.io"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[languages.en.menu.topbar]]
    weight = 3
    name = "Facebook"
    url = "https://www.facebook.com/selabnaist/"
    pre = "<i class='fab fa-2x fa-facebook'></i>"

[[languages.en.menu.topbar]]
    weight = 4
    name = "Twitter"
    url = "https://twitter.com/naistselab"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[params]
    viewMorePostLink = "/news/"
    author = "SE-lab"
    defaultKeywords = ["selab", "naist", "software engineering"]
    mainSections = ["news"]
    defaultDescription = "Offical side to se-naist"
    
    # Social media
    facebook_site = "https://www.facebook.com/selabnaist/" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "https://twitter.com/naistselab" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/graduation-m2-2022-03.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    dropdown_mouse_over = false

    disabled_logo = false
    logo_text = "SE Lab"

    logo = "img/logo.png"
    logo_small = "img/logo-selab.png"
    access = "/access"

[permalinks]
    news = "/news/:year/:month/:day/:filename/"
    
# Enable or disable top bar with social icons
[languages.ja.params.topbar]
    enable = true
    text = """<p class="hidden-sm hidden-xs"> Software Engineering Lab at NAIST</p>
      """

# Enable and disable widgets for the right sidebar
[languages.ja.params.widgets]
    categories = true
    tags = true
    search = true

[params.carouselCustomers]
    items = 1
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[params.carouselTestimonials]
    items = 3
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000


[languages.ja.params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "学生"
    subtitle = ""
    
[params.carouselHomepage]
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more information take a look at the README.
    enable = true
    auto_play = true
    slide_speed = 2000
    pagination_speed = 1000

[languages.ja.params.recent_posts]
    enable = true
    title = "ニュース"
    subtitle = ""
    hide_summary = true

[languages.en.params.recent_posts]
    enable = true
    title = "Recent news"
    subtitle = ""
    hide_summary = true

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"

[server]
[[server.headers]]
  for = "/*"
    [server.headers.values]
    Access-Control-Allow-Origin = "*"